dist: trusty
language: generic
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=mips-unknown-linux-musl
    - env: TARGET=mipsel-unknown-linux-musl
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=arm-unknown-linux-gnueabihf
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i586-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=mips-unknown-linux-gnu
    - env: TARGET=mipsel-unknown-linux-gnu
    - env: TARGET=powerpc-unknown-linux-gnu
    - env: TARGET=powerpc64-unknown-linux-gnu
    - env: TARGET=powerpc64le-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
  allow_failures:
    # rust-lang/rust#35599 catch_unwind broken
    - env: TARGET=i686-unknown-linux-musl
    # Ubuntu 16.04: Broken QEMU (apparently)
    - env: TARGET=powerpc64le-unknown-linux-gnu

install:
  - git clone --depth 1 https://github.com/rust-lang/libc

script:
  - bash ci/script.sh

branches:
  only:
    - master

notifications:
  email:
    on_success: never
